let
  makeKeyMap = m: k: e: d:
    {
      mode = m;
      key = k;
      effect = e;
      docstring = d;
    };
in
[
  (makeKeyMap "normal" "n" "j" null)
  (makeKeyMap "normal" "e" "k" null)
  (makeKeyMap "normal" "i" "l" null)
  (makeKeyMap "normal" "k" "n" null)
  (makeKeyMap "normal" "l" "u" null)
  (makeKeyMap "normal" "j" "e" null)
  (makeKeyMap "normal" "u" "i" null)
  (makeKeyMap "normal" "N" "J" null)
  (makeKeyMap "normal" "E" "K" null)
  (makeKeyMap "normal" "I" "L" null)
  (makeKeyMap "normal" "K" "N" null)
  (makeKeyMap "normal" "L" "U" null)
  (makeKeyMap "normal" "J" "E" null)
  (makeKeyMap "normal" "U" "I" null)
  (makeKeyMap "normal" "<a-n>" "<a-j>" null)
  (makeKeyMap "normal" "<a-e>" "<a-k>" null)
  (makeKeyMap "normal" "<a-i>" "<a-l>" null)
  (makeKeyMap "normal" "<a-k>" "<a-n>" null)
  (makeKeyMap "normal" "<a-l>" "<a-u>" null)
  (makeKeyMap "normal" "<a-j>" "<a-e>" null)
  (makeKeyMap "normal" "<a-u>" "<a-i>" null)
  (makeKeyMap "normal" "<a-N>" "<a-J>" null)
  (makeKeyMap "normal" "<a-E>" "<a-K>" null)
  (makeKeyMap "normal" "<a-I>" "<a-L>" null)
  (makeKeyMap "normal" "<a-K>" "<a-N>" null)
  (makeKeyMap "normal" "<a-L>" "<a-U>" null)
  (makeKeyMap "normal" "<a-J>" "<a-E>" null)
  (makeKeyMap "normal" "<a-U>" "<a-I>" null)
  (makeKeyMap "normal" "<c-n>" "<c-j>" null)
  (makeKeyMap "normal" "<c-e>" "<c-k>" null)
  (makeKeyMap "normal" "<c-i>" "<c-l>" null)
  (makeKeyMap "normal" "<c-k>" "<c-n>" null)
  (makeKeyMap "normal" "<c-l>" "<c-u>" null)
  (makeKeyMap "normal" "<c-j>" "<c-e>" null)
  (makeKeyMap "normal" "<c-u>" "<c-i>" null)
  (makeKeyMap "normal" "<c-N>" "<c-J>" null)
  (makeKeyMap "normal" "<c-E>" "<c-K>" null)
  (makeKeyMap "normal" "<c-I>" "<c-L>" null)
  (makeKeyMap "normal" "<c-K>" "<c-N>" null)
  (makeKeyMap "normal" "<c-L>" "<c-U>" null)
  (makeKeyMap "normal" "<c-J>" "<c-E>" null)
  (makeKeyMap "normal" "<c-U>" "<c-I>" null)
  (makeKeyMap "normal" "<c-a-n>" "<c-a-j>" null)
  (makeKeyMap "normal" "<c-a-e>" "<c-a-k>" null)
  (makeKeyMap "normal" "<c-a-i>" "<c-a-l>" null)
  (makeKeyMap "normal" "<c-a-k>" "<c-a-n>" null)
  (makeKeyMap "normal" "<c-a-l>" "<c-a-u>" null)
  (makeKeyMap "normal" "<c-a-j>" "<c-a-e>" null)
  (makeKeyMap "normal" "<c-a-u>" "<c-a-i>" null)
  (makeKeyMap "normal" "<c-a-N>" "<c-a-J>" null)
  (makeKeyMap "normal" "<c-a-E>" "<c-a-K>" null)
  (makeKeyMap "normal" "<c-a-I>" "<c-a-L>" null)
  (makeKeyMap "normal" "<c-a-K>" "<c-a-N>" null)
  (makeKeyMap "normal" "<c-a-L>" "<c-a-U>" null)
  (makeKeyMap "normal" "<c-a-J>" "<c-a-E>" null)
  (makeKeyMap "normal" "<c-a-U>" "<c-a-I>" null)
  (makeKeyMap "insert" "<c-b>" "<left>" null)
  (makeKeyMap "insert" "<c-f>" "<right>" null)
  (makeKeyMap "insert" "<c-a>" "<esc>I" null)
  (makeKeyMap "insert" "<c-e>" "<end>" null)
  (makeKeyMap "insert" "<a-b>" "<esc>b;i" null)
  (makeKeyMap "insert" "<a-f>" "<esc>w;i" null)
  (makeKeyMap "insert" "<c-d>" "<esc>c" null)
  (makeKeyMap "insert" "<c-k>" "<esc><a-l>c" null)
  (makeKeyMap "insert" "<c-w>" "<esc>bc" null)
  (makeKeyMap "prompt" "<c-b>" "<left>" null)
  (makeKeyMap "prompt" "<c-f>" "<right>" null)
  (makeKeyMap "prompt" "<c-a>" "<home>" null)
  (makeKeyMap "prompt" "<c-e>" "<end>" null)
  (makeKeyMap "goto" "n" "j" "buffer bottom")
  (makeKeyMap "goto" "e" "k" "buffer top")
  (makeKeyMap "goto" "i" "l" "line end")
  (makeKeyMap "goto" "j" "e" "buffer end")
  (makeKeyMap "goto" "u" "i" "line non-blank start")
  (makeKeyMap "view" "n" "j" "scroll down")
  (makeKeyMap "view" "e" "k" "scroll up")
  (makeKeyMap "view" "i" "l" "scroll right")
  (makeKeyMap "user" "w" ":w<ret>" "save buffer")
  (makeKeyMap "user" "b" ":b " "switch buffer")
  (makeKeyMap "user" "m" ":make<ret>" "make")
  (makeKeyMap "user" "l" ":enter-user-mode lsp<ret>" "LSP mode")
]
